### ISSUE TITLE
 IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by Rom1deTroyes** [Camebush/real-time-yolov4-object-detection#1]
Bonjour,

En lançant le code avec Python 3.9.2, j'ai une erreur :

```python
Traceback (most recent call last):
  File "/home/romain/Documents/Projets/Yolo/yolo-object-detection.py", line 7, in <module>
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "/home/romain/Documents/Projets/Yolo/yolo-object-detection.py", line 7, in <listcomp>
    ln = [ln[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.
```
Merci pour les vidéos et le partage, c'est motivant :1st_place_medal:

**Comment by Rom1deTroyes** [comment]
Quelques précisions :

opencv-python==4.5.5.64

Et un contournement : 
```python
ln = [ln[i-1] for i in net.getUnconnectedOutLayers()]
```
